language: python

python:
    - "2.7"

sudo: enabled

install:
  - pip install -r requirements.txt
  - pip install -r pdist/requirements.txt
  - pip install -r weighted_k_means/requirements.txt

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cd pdist
  - make
  - make test
  - cd ..

script:
  - make test
